### ISSUE TITLE
Set up Firebase, including tests [10h]

### ISSUE THREAD

**Issue by SolalPirelli** [2018-SWENG/2018-SWENG-Radius#4]

**Comment by X4l1b1** [comment]
- Most time spent on reading documentation and fighting with library imports, version conflict, etc.. API BS
- Unable (so far) to implement Unit Tests (no usable example, unreseolved FirebaseAPI generated exception)

### Next Step

- Implement manual test in app using buttons to test CRUD operations with database

**Comment by X4l1b1** [comment]
- Most time spent on reading documentation and fighting with library imports, version conflict, etc.. API BS 
- Unable (so far) to implement Unit Tests (no usable example, unreseolved FirebaseAPI generated exception)  
#### Next Step  
- Implement manual test in app using buttons to test CRUD operations with database
--
